version: 0.0
os: linux

files:
  - source: frontend/dist/
    destination: /var/www/html/

hooks:
  BeforeInstall:
    - location: frontend/deploy-scripts/start.sh
      timeout: 120
      runas: root