version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd frontend && npm ci
  build:
    commands:
      - pwd
      - ls -al
      - npm run build
      - pwd && ls -al
      - cp appspec.yml ../appspec.yml || cp frontend/appspec.yml appspec.yml
      - cp -r deploy-scripts ../deploy-scripts || cp -r frontend/deploy-scripts deploy-scripts

artifacts:
  files:
    - frontend/dist/**/*
    - deploy-scripts/**/*
    - appspec.yml
  discard-paths: no

cache:
  paths:
    - frontend/node_modules/**/*